name:                applicatives-validation
version:             0.1.0.0
github:              "enolive/applicatives-validation"
license:             BSD3
author:              "Christoph Welcz"
maintainer:          "christoph@welcz.de"
copyright:           "2018 Christoph Welcz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/enolive/applicatives-validation#readme>

dependencies:
- base >= 4.7 && < 5
- validation

ghc-options: -Wall

executables:
  applicatives-validation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
